name: React CI

on:
    pull_request:
        branches:
            - main

jobs:
    react-check:
        name: React check
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: frontend
        
        steps:
            - name: Descargar repositorio
              uses: actions/checkout@v4

            - name: Configurar Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 22
                cache: npm
                cache-dependency-path: frontend/package-lock.json
            
            - name: Instalar dependencias
              run: npm ci

            - name: Ejecutar ESLint
              run: npm run lint
            
            - name: Comprobar build
              run: npm run build